import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Course() {
  return (
    <div className="container">
      <Head>
        <title>Edi Prastyo | Works</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <header>
            <nav className="flex flex-row justify-between items-center py-5 border-gray-white border-b">
              <Link className="font-medium text-2xl text-blue-dark" href="/">
                Edi.
              </Link>
              <div className="w-full text-end">
                <Link
                  href="/"
                  className="font-light text-gray-light underline hover:text-blue-primary"
                >
                  Back
                </Link>
              </div>
            </nav>
          </header>

          <section id="works">
            <div className="py-6">
              <h3 className="font-medium text-2xl text-blue-primary">Works</h3>
              <p className="font-light text-gray-light">
                Some of the projects I have worked on
              </p>
              <div className="mt-4 flex flex-col gap-6">
                <div className="w-full">
                  <div className="w-full rounded-lg mb-5 overflow-hidden">
                    <Image
                      className="w-full h-56 object-cover"
                      src="/cover-course.jpg"
                      alt="Picture of the author"
                      width={500}
                      height={300}
                    />
                  </div>
                  <h5 className="text-blue-dark text-xl mb-3">
                    Online Course Landing Page
                  </h5>
                  <small className="text-gray-light">Description</small>
                  <p className="text-blue-dark mb-4">
                    A landing page for online course. Online course is a program
                    of learning that&apos;s organized according to a syllabus
                    and that takes place in a virtual space. Provide many
                    categories of learning class.
                  </p>
                  <small className="text-gray-light">Technology</small>
                  <div className="w-full mt-2 mb-4 flex flex-wrap gap-2">
                    <div className="skill-item">
                      <p>HTML</p>
                    </div>
                    <div className="skill-item">
                      <p>CSS</p>
                    </div>
                    <div className="skill-item">
                      <p>TailwindCSS</p>
                    </div>
                  </div>
                  <small className="text-gray-light">Result</small>
                  <div>
                    <a
                      href="https://ediprast.github.io/course-landingpage/"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="font-light text-blue-primary underline hover:text-blue-dark mr-4"
                    >
                      Live Demo
                    </a>
                    <a
                      href="https://github.com/ediprast/course-landingpage"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="font-light text-blue-primary underline hover:text-blue-dark"
                    >
                      Github
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </main>

      <footer className="w-full border-t border-gray-white py-5">
        <p className="font-light text-gray-light text-center">
          Copyright 2022 • All rights reserved • Edi Prastyo
        </p>
      </footer>
    </div>
  );
}
